### ISSUE TITLE
FYI: injectable_generator never completes with build_runner 1.10.0 (which is the default version)

### ISSUE THREAD

**Issue by dalewking** [Milad-Akarie/injectable#112]
Was trying to throw together a quick project to demonstrate the capitalization bug I reported. Rather than specify the version I just put this in pubspec.yaml:

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
```

and if you run build_runner it never completes. The version of build_runner it loaded is 1.10.0 and you see the same thing if you explicitly specify that version. It works fine with build_runner 1.10.1.

Not sure there is anything you can do about that, but just letting you know.
