### ISSUE TITLE
Auto registering LazySingleton and Singleton?

### ISSUE THREAD

**Issue by raimsargado** [Milad-Akarie/injectable#135]
Hi @Milad-Akarie. Thank you for creating this package!

I like how it has an option to auto register a single injectable.  
Right now I can auto register my Bloc or by far any convention using the sample config below: 
```
targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # auto registers any class with a name matches the given pattern
          class_name_pattern:
            "Bloc$"
            # auto registers any class inside a file with a
            # name matches the given pattern
          file_name_pattern: "_bloc$"
```
From the config above if I can do this: 
```
class MyBloc {}
```
it auto registers as follows: 
```
void $initGetIt(GetIt g, {String environment}) {
   g.registerFactory<MyBloc>(() => MyBloc());
}
```

What I would like to know is, if there is a way to auto register an implementing class and auto register an intended singleton class?

As an example:  

This implementing class:
```
class MyRepo extends RepoInterface {}
```
then should auto register as follows: 
```
void $initGetIt(GetIt g, {String environment}) {
   g.registerLazySingleton<RepoInterface>(() => MyRepo());
}
```

And this intended singleton class: 
```
class MyClass {}
```
then should auto register as follows: 
```
void $initGetIt(GetIt g, {String environment}) {
   g.registerSingleton<MyClass>(() => MyClass());
}
```
