### ISSUE TITLE
Version conflict when doing pub get

### ISSUE THREAD

**Issue by VNAPNIC** [Milad-Akarie/injectable#280]
``` cmd
Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.20.0 depends on test_api 0.4.9, test >=1.16.0-nullsafety.19 requires test_api 0.2.19 or 0.4.9 or analyzer >=1.0.0 <3.0.0.
Because no versions of injectable_generator match >1.5.3 <2.0.0 and injectable_generator 1.5.3 depends on analyzer ^3.0.0, injectable_generator ^1.5.3 requires analyzer ^3.0.0.
Thus, if injectable_generator ^1.5.3 and test >=1.16.0-nullsafety.19 then test_api 0.2.19 or 0.4.9.
And because every version of flutter_test from sdk depends on test_api 0.4.8, one of injectable_generator ^1.5.3 or test >=1.16.0-nullsafety.19 or flutter_test from sdk must be false.
And because bloc_test >=8.0.0-nullsafety.5 depends on test ^1.16.0 and position_exchange depends on flutter_test from sdk, injectable_generator ^1.5.3 is incompatible with bloc_test >=8.0.0-nullsafety.5.
So, because position_exchange depends on both bloc_test ^9.0.2 and injectable_generator ^1.5.3, version solving failed.
pub get failed (1; So, because position_exchange depends on both bloc_test ^9.0.2 and injectable_generator ^1.5.3, version solving failed.)
```

``` yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  retrofit_generator: any
  mockito: ^5.0.10
  json_serializable: ^6.1.4
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.0

```
