### ISSUE TITLE
Flutter3 lint warning

### ISSUE THREAD

**Issue by P-B1101** [Milad-Akarie/injectable#288]
Thanks for great package.
In flutter 3 upgrade for lint package there is a warning in generated file.

`Avoid leading underscores for library prefixes.`

I had to add ignore line in the top of the generated file every time it's regenerated.
it would be great if you could remove `_` from library prefixes.
Thanks again.

**Comment by leoshusar** [comment]
You exclude all generated files from analysis, there's IMHO no real reason to not do this.

analysis_options.yaml
```yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.config.dart"
```
