### ISSUE TITLE
Analyzer 4.2.0

### ISSUE THREAD

**Issue by rokk4** [Milad-Akarie/injectable#296]
Please update the analyzer dependency. Thanks.

**Comment by guyluz11** [comment]
Pull request to bump the version to 4.0.0 #283

Maybe connected to #280

**Comment by chrisfraser** [comment]
I have #297 open to fix this.

Temporary solution:
```
  injectable_generator:
    git:
      url: https://github.com/chrisfraser/injectable.git/
      ref: master
      path: injectable_generator
```
