### ISSUE TITLE
Analyzer ^5.0.0

### ISSUE THREAD

**Issue by sedobrengocce** [Milad-Akarie/injectable#311]
please update again analyzer dependency

**Comment by dJani97** [comment]
Until [this PR](https://github.com/Milad-Akarie/injectable/pull/310) is merged, you can use the updated version like so:
```yaml
injectable_generator:
  git:
    url: https://github.com/amondnet/injectable.git
    path: injectable_generator
```
