### ISSUE TITLE
Sealed-class error

### ISSUE THREAD

**Issue by marcinFDT** [Milad-Akarie/injectable#373]
Hey, I struggle with this problem

```
[SEVERE] injectable_generator:injectable_builder on lib/XXX/xxx/xxx.dart:

This builder requires Dart inputs without syntax errors.
However, package:XXX/xxx/xxx.dart (or an existing part) contains the following errors.
xxx.dart:5:1: This requires the 'sealed-class' language feature to be enabled.

Try fixing the errors and re-running the build.
```

```
@immutable
sealed class xxx<T> {
  const xxx();
}
```

```
Env:
Flutter (Channel stable, 3.10.5)
Dart SDK version: 3.0.5 (stable) 

yaml:
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
   get_it: ^7.6.0
   injectable: ^2.1.2
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6

```

For some reason I cannot use dart 3.0 features with this lib. I can run the app without any syntax problems but the error appear after running the build_runner.

It's the problem on the lib side? or I have something wrong? 🤔
