### ISSUE TITLE
Receiving InvalidType is not a class element using the builder greater than 2.3.3

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [Milad-Akarie/injectable#375]
I can't use the package [`i18n`](https://pub.dev/packages/i18n) with `injectable`. The `Messages` are generated correctly, but not the `MessagesModule`. I'm receiving the error `InvalidType is not a class element`. Any idea how to fix this?

Here is my pubspec.yaml:
```yaml
dependencies:
  flutter:
    sdk: flutter
  i18n: ^4.0.3
  injectable: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.0
  injectable_generator: ^2.1.6
```
My Module:
```dart
@module
abstract class MessagesModule {
  @singleton
  Messages createMessages() {
    return const Messages();
  }
}
```
My messages.18n.yaml:
```yaml
appName: MyApp
```

**Comment by migalv** [comment]
Similar issue for me when trying to register a module for the `dio` package.

```
@module
abstract class DioClientModule {
  @LazySingleton(env: [Environment.prod])
  Dio prodDioClient() => Dio(
        BaseOptions(
          baseUrl: host,
          receiveTimeout: defaultReceiveTimeout,
          connectTimeout: defaultConnectTimeout,
          followRedirects: false,
          validateStatus: (status) => status != null && status < 500,
        ),
      )..interceptors.add(CookieManager(CookieJar()));
}
```

```
[SEVERE] injectable_generator:injectable_builder on lib/infrastructure/core/injectable_modules.dart (cached):

InvalidType is not a class element
```

Could it be because the Dio class is abstract then the builder is failing because of it?

**Comment by Milad-Akarie** [comment]
@migalv it shouldn't care about that because you're initiating your self, try making prodDioClient a getter instead of a method?

**Comment by migalv** [comment]
Hey @Milad-Akarie thanks for the quick reply!

I've dug down a little more into my issue, by adding prints into the source code (I think this could be improved to give a bit more info on the problem) and I've found out the problem has to do with me registering the AppRouter from the `auto_route` package.

This was working fine until a few days ago when Flutter released the new version to the stable channel. 

After updating Flutter to v3.13.0 & Dart v3.1.0

My code generation has broken.

It was working perfectly fine for versions v3.10.6 & Dart v3.0.7

Here is my `flutter doctor` output

```
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F82 darwin-arm64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

I'm using Injectable to generate my factory registration.

But I'm getting `InvalidType is not a class element` error

It seems this is thrown when trying to register the External Module AppRouter from the `auto_route` package.

Here is the code for the External module. Fairly straightforward
```
@module
abstract class AppRouterModule {
  @singleton
  AppRouter get appRouter => AppRouter();
}
```

I've tried switching between different `build_runner` versions but nothing has worked

**Comment by Milad-Akarie** [comment]
Hey @migalv if that's the case then maybe try to force generating order using build.yaml config

```yaml
targets:
  $default:
    builders:
      auto_route_generator:auto_router_generator:
        runs_before:
          - injectable_generator:injectable_builder
          - injectable_generator:injectable_config_builder
```

**Comment by migalv** [comment]
Hey thanks a lot for the fast reply @Milad-Akarie 

I tried what you said but I'm getting this error:

`Invalid argument(s): line 21, column 9 of build.yaml: Unrecognized keys: [runs_before];`

I also tried this configuration for the build.yaml file. But to be honest I have no idea about the build.yaml format. Maybe you can find my problem (I'm still getting the same `InvalidType` error with this config)

```
builders:
  injectable_generator:
    import: "package:injectable_generator/builder.dart"
    builder_factories: ["injectableBuilder", "injectableConfigBuilder"]
    build_extensions: { ".dart": [".config.dart"] }
    auto_apply: dependents
    build_to: source

  auto_route_generator:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: ["autoRouteGenerator"]
    build_extensions: { ".dart": [".gr.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - injectable_generator
```
