### ISSUE TITLE
Auto register with option to register the class as its interface

### ISSUE THREAD

**Issue by fatshady** [Milad-Akarie/injectable#376]
I found the auto_register option useful to automatically inject classes that are generated with build_runner since you cannot add any of the annotation such as @Singleton, @Injectable etc to the auto generated code. 
It would be useful to add an option to the build.yaml to tell the generator to inject the class as the interface it implements, as you whould do with @Injectable(as: myInterface). 

i mean something like 

```
injectable_generator:injectable_builder:
        options:
          auto_register: true
          registerAsInterface: true <<-- THIS
          # auto registers any class with a name matches the given pattern
          class_name_pattern: "Service$|Repository$|^Mock"
          # auto registers any class inside a file with a
          # name matches the given pattern
          file_name_pattern: "_service$|_repository$"
```

this would be very useful to respect the inversion of control principles while injecting auto-generated classes.
For example this would work perfectly along with the Mockito package since you can have the auto-generated mock to be injected as its interface automatically.

so, given a class that must be tested that uses a repository

```
class ClassUnderTest {
     final repo = GetIt.I<ActivityDetailsRepositoryInterface>();

     int countOfItemInRepo() async {
        var result= await repo.getAll();
        return result.length;
     }
}

abstract class ActivityDetailsRepositoryInterface {
  Future<List<ActivityDetailsEntity>> getAll();
}
```

and a test class

```
//Tell Mockito to generate a mock for the repo
@GenerateMocks([
  ActivityDetailsRepositoryInterface
])
void main() {
  group("group", () {
    test('myTest', () async {
        //I can mock the behaviour of the repo retrieving it through getIt
        ActivityDetailsRepositoryInterface repo =
        GetIt.I<ActivityDetailsRepositoryInterface>() as MockActivityDetailsRepositoryInterface;
         when(repo.getAll()).thenAnswer((_) => Future<List<ActivityDetailsEntity>>.value([]));
       
        ClassUnderTest class = ClassUnderTest(); //no errors since GetIt can be found the injected interface class 
        var result = class.countOfItemInRepo();
        expect(result, 0);
    });

  });
}
```

mockito generates:

```
class MockActivityDetailsRepositoryInterface extends _i1.Mock
    implements _i13.ActivityDetailsRepositoryInterface { //here is the interface that should be used for the injection
     //content omitted
}
```

then i expect ad injection code that looks like:

```
gh.factory<_i5.ActivityDetailsRepositoryInterface>(//injected as its interface
      () => _i5.MockActivityDetailsRepositoryInterface()); //inject the real mock implementation
```

I hope I've been clear in my explanation.
Thank you for the time spent reading through this.
