### ISSUE TITLE
Different dependency ordering with the same code

### ISSUE THREAD

**Issue by mozerrr** [Milad-Akarie/injectable#404]
Running `flutter packages run build_runner build --delete-conflicting-outputs` can produce different imports and dependency ordering with the same code.
<img width="980" alt="изображение" src="https://user-images.githubusercontent.com/24671272/209943108-133f44ce-b74d-49db-bf60-0fb79b285eea.png">
It's not a problem until you trying to use build_verify that fails if something changed.
```
Expected: empty
  Actual: 'diff --git a/lib/di/injectable.config.dart b/lib/di/injectable.config.dart\n'
```

injectable: 2.1.0
injectable_generator: 2.1.3
build_runner: 2.3.0
build_verify: 3.1.0
dart: 2.18.4
flutter: 3.3.8

Original issue https://github.com/Milad-Akarie/injectable/issues/337 , https://github.com/Milad-Akarie/injectable/issues/371

**Comment by Milad-Akarie** [comment]
@mozerrr hmm not sure what to do here, I'm sorting deps alphabetically then by dependent.

**Comment by Adam-Langley** [comment]
It looks like the ordering needs to take into account more than just the name of the dependency,  as the dependency can be registered multiple times, as affected by environment, or naming.

Here is an example of the same "churn" caused by multi-registration of the same dependency, both named, and unnamed.

See how "factoryParamAsync<_i43.EnergySourceDetailStore..." (the unnamed version) moves from before the named version (instanceName: "_") to after it.

<img width="1444" alt="image" src="https://github.com/Milad-Akarie/injectable/assets/16373742/d792d9a4-0e49-447c-841a-56894f4d7d3a">

**Comment by mxnortal** [comment]
My team faced the same problem. Every time we generate injectable config with the same code, it outputs different file. 
As a result, we have code changes and thus regular merge conflicts. In the present time we get injectable merge conflict **in every PR.** This inejctable config became a nightmare, causing constant merge conflicts hell.
I dont know how nobody talks about this problem. In a big team (like >5 devs) this lib isnt usable

**Comment by mozerrr** [comment]
not stale

**Comment by Adam-Langley** [comment]
Hi everyone,
I think I've pipped this issue - some testing would be appreciated due to the non-deterministic nature of the errant behaviour.

You can try it out by adding these dependency overrides to your pubspec.yaml

```
dependency_overrides:
  injectable:
    git:
      url: https://github.com/Adam-Langley/injectable.git
      path: injectable/
      ref: fix/nondeterministic-dependency-ordering

  injectable_generator:
    git:
      url: https://github.com/Adam-Langley/injectable.git
      path: injectable_generator/
      ref: fix/nondeterministic-dependency-ordering
```

Note: you will probably encounter churn in your generated code as soon as you apply this override, as it's applying much more strict ordering to the dependencies (hence eliminating the non-determinism) - but then subsequence regenerations should be identical (assuming your dont change your depedency config of course :)
