### ISSUE TITLE
The annotation 'preResolve' can only be used on methods. 

### ISSUE THREAD

**Issue by jamontes79** [Milad-Akarie/injectable#447]
After upgrading to the latest version `2.4.1`, I'm getting the following warning in one of the examples used in the documentation:

`The annotation 'preResolve' can only be used on methods`

```dart
@module
abstract class RegisterModule {
  @preResolve
  Future<SharedPreferences> get prefs => SharedPreferences.getInstance();
}
```

**Comment by user97116** [comment]
same

**Comment by phamconganh** [comment]
in analysis_options.yaml
```
analyzer:
  exclude:
    - "**/locale_keys.g.dart"
  #   - "**/*.g.dart"
  #   - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore # hotfix for freezed @JsonKey and injectable @preResolve
```
