### ISSUE TITLE
How to change generated output ?

### ISSUE THREAD

**Issue by EArminjon** [Milad-Akarie/injectable#497]
I want to put all my generated code inside a generated folder. At root or at file level it doesn't matter. How. to do that with injectable ?

**Comment by nathnaeld** [comment]
I’ve also tried to achieve something similar — moving the generated `*.config.dart` files into a dedicated folder — but without success.

For example, I attempted the following in `build.yaml`:

```yaml
targets:
  $default:
    builders:
      # Default build_runner
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/core/injector/{{file}}.dart':
              'lib/generated/injector/{{file}}.config.dart'

      # Maybe Injectable
      injectable_generator|injectable_config_builder:
        options:
          build_extensions:
            'lib/core/injector/{{file}}.dart':
              'lib/generated/injector/{{file}}.config.dart'
```

Unfortunately, the generated file is still created next to the source file with `@InjectableInit()`.

It would be really helpful if `injectable` allowed us to configure an output directory for generated files, similar to how other code generators let us organize outputs.
